version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    command: [
      "sh", "-c",
      "uvicorn src.api.app:app --host $API_HOST --port $API_PORT --reload"
    ]
    tty: true
